# This configuration is for the final dataset for the entire Australian region.
land_mask_path: "data/in-3p/ne_10m_land/ne_10m_land.shp"
grid_bbox: [96, -44, 169, -7]
grid_cell_size: 0.03125
land_overlap_px: 2
grid_path: "working/EOT20-au/grid.tif"
tide_model_path: "data/in-3p/World_EOT20_2021/ocean_tides"
clipped_tide_model_path: "working/EOT20-au/ocean_tides"
clipping_buffer_deg: 0.25
start_date: "2005-01-01"
end_date: "2024-12-01"
time_step: 0.5
working_path: "working/EOT20-au/tmp"
lat_label: 'LAT'
hat_label: 'HAT'
output_path_prefix: "data/out/AU_AIMS_EOT20-tide-stats_"
author: "Eric Lawrey"
organization: "Australian Institute of Marine Science"
description: "Tidal statistics derived from EOT20 using pyTMD run over 19 years (2005 - 2024)."
reference: "Tidal Statistics for Australia (Tidal range, LAT, HAT, MLWS, MHWS, Percentiles) derived from the EOT20 tidal model (NESP MaC 3.17, AIMS) (V1) [Data set]. eAtlas. https://doi.org/10.26274/z8b6-zx94"
metadata_link: "https://doi.org/10.26274/z8b6-zx94"
license: "CC-BY 4.0"
percentiles: [1, 2, 5, 10, 20, 50, 80, 90, 95, 98, 99]