# This is a longer test suitable for parallel testing. 
# This test takes approximately 1 hr 20 mins on a single core.
land_mask_path: "in-data-3p/ne_10m_land/ne_10m_land.shp"
grid_bbox: [111, -27, 154, -9]
grid_cell_size: 0.0625
land_overlap_px: 2
grid_path: "working/EOT20-nau-test/grid.tif"
tide_model_path: "in-data-3p/World_EOT20_2021/ocean_tides"
clipped_tide_model_path: "working/EOT20-nau-test/ocean_tides"
clipping_buffer_deg: 0.25
start_date: "2023-01-01"
end_date: "2023-12-01"
time_step: 0.5
working_path: "working/EOT20-nau-test/tmp"
lat_label: 'LPT'
hat_label: 'HPT'
output_path_prefix: "working/EOT20-nau-test/"
author: "Eric Lawrey"
organization: "Australian Institute of Marine Science"
description: "Tidal statistics derived from EOT20 using pyTMD run over 1 year."
reference: "This is only test data"
metadata_link: ""
license: "CC-BY 4.0"